Repository team2-freeOnBorading/modu-todo, pull requests merged in 2021-08, with the labels that each got.

#6 style: 스타일 초기화 파일 추가
  package-lock.json
  package.json
  src/index.tsx
  src/style/global.js
Labels: feature

#9 chore : window환경 prettier CR 에러 해결 옵션 추가
  .eslintrc
Labels: setting

#11 Feat: header layout
  package-lock.json
  package.json
  src/components/TodoHeader/TodoFilter/TodoFilter.tsx
  src/components/TodoHeader/TodoHeader.tsx
  src/utils/constants.ts
Labels: feature

#13 chore : type 수정
  src/type.ts
Labels: feature

#15 feat : todoitem 레이아웃
  package-lock.json
  package.json
  public/index.html
  src/components/TodoList/TodoItem/TodoItem.tsx
  src/components/TodoList/TodoList.tsx
  src/style/global.ts
Labels: feature

#16 fix: header UI 수정
  src/components/TodoHeader/TodoFilter/TodoFilter.tsx
  src/components/TodoHeader/TodoHeader.tsx
Labels: feature

#19 TodoKanban, TodoList, TodoItem 생성 및 스타일링 , Merge Conflict까지 수정
  src/App.tsx
  src/components/TodoFooter/TodoFooter.tsx
  src/components/TodoHeader/TodoFilter/TodoFilter.tsx
  src/components/TodoHeader/TodoHeader.tsx
  src/components/TodoKanban/TodoItem/TodoItem.tsx
  src/components/TodoKanban/TodoKanBan.tsx
  src/components/TodoKanban/TodoList/TodoList.tsx
  src/components/TodoList/TodoList.tsx
  src/type.ts
Labels: feature, style, fix, chore

#20 Feat : header icon, button 추가
  src/components/TodoHeader/TodoFilter/TodoFilter.tsx
  src/components/TodoHeader/TodoHeader.tsx
  src/type.ts
  src/utils/constants.ts
Labels: feature

#26 chore : Todo컴포넌트 사용 순서 변경
  src/App.tsx
  src/components/TodoKanban/TodoKanBan.tsx
  src/components/TodoKanban/TodoList/TodoList.tsx
Labels: chore

#27 chore: type 수정
  src/type.ts
Labels: chore

#28 chore: commons 함수 추가
  src/utils/commons.ts
Labels: chore

#31 Todo CRUD 및 로컬스톨리지 기능 구현 완료
  src/App.tsx
  src/components/TodoHeader/TodoFilter/TodoFilter.tsx
  src/components/TodoKanban/TodoItem/TodoItem.tsx
  src/components/TodoKanban/TodoKanBan.tsx
  src/components/TodoKanban/TodoList/TodoList.tsx
  src/components/common/Modal/FilterModal/FilterModal.tsx
  src/components/common/Modal/FilterModal/index.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/Modal/SortModal.tsx
  src/components/common/Modal/TestModal.tsx
  src/context/TodoContext.tsx
  src/context/actions.ts
  src/hooks/useStorage.ts
  src/index.tsx
  src/type.ts
Labels: feature

#33 dateTostring 함수 리펙토링
  src/App.tsx
  src/utils/commons.ts
Labels: refactor
